# Generated by Django 3.0.1 on 2021-04-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taxid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('Symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taxid', models.IntegerField()),
                ('Alias', models.ManyToManyField(to='Distance.AliasName')),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Chrom', models.CharField(max_length=255)),
                ('Start', models.IntegerField()),
                ('End', models.IntegerField()),
                ('taxid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell', models.CharField(max_length=255)),
                ('Condition', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('Probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='Distance.Probe')),
            ],
            options={
                'unique_together': {('Probe', 'Cell', 'Condition')},
            },
        ),
        migrations.CreateModel(
            name='GeneProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('Gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geneprobe', to='Distance.Gene')),
                ('Probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geneprobe', to='Distance.Probe')),
            ],
            options={
                'unique_together': {('Gene', 'Probe')},
            },
        ),
    ]
