# Generated by Django 3.0.1 on 2021-03-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('Symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Alias', models.ManyToManyField(to='Distance.AliasName')),
            ],
        ),
    ]
