# Generated by Django 3.0.1 on 2021-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasname',
            name='taxid',
            field=models.IntegerField(default=9606),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='taxid',
            field=models.IntegerField(default=9606),
            preserve_default=False,
        ),
    ]
