# Generated by Django 3.2.4 on 2021-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.CharField(max_length=255)),
                ('Chrom_A', models.CharField(max_length=255)),
                ('Chrom_B', models.CharField(max_length=255)),
                ('histogram_mean', models.JSONField()),
                ('histogram_std', models.JSONField()),
            ],
            options={
                'unique_together': {('Chrom_A', 'Chrom_B', 'Condition')},
            },
        ),
    ]
