# Generated by Django 3.2.4 on 2021-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0002_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='TSS',
            field=models.IntegerField(null=True),
        ),
    ]
