# Generated by Django 3.0.1 on 2021-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0002_auto_20210401_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Chrom', models.CharField(max_length=255)),
                ('Start', models.IntegerField()),
                ('End', models.IntegerField()),
                ('taxid', models.IntegerField()),
            ],
        ),
    ]
