# Generated by Django 3.2.4 on 2021-06-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0003_gene_tss'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='Chrom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
