# Generated by Django 3.0.1 on 2021-04-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0003_probe'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('Gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geneprobe', to='Distance.Gene')),
                ('Probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geneprobe', to='Distance.Probe')),
            ],
        ),
    ]
