# Generated by Django 3.0.1 on 2021-04-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0004_geneprobe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geneprobe',
            unique_together={('Gene', 'Probe')},
        ),
    ]
