# Generated by Django 3.0.1 on 2021-04-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distance', '0005_auto_20210401_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell', models.CharField(max_length=255)),
                ('Condition', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('Probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='Distance.Probe')),
            ],
            options={
                'unique_together': {('Probe', 'Cell', 'Condition')},
            },
        ),
    ]
